WebLab1_Levchenko/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebLab1_Levchenko.Components
{
    public class MenuViewComponent: ViewComponent
    {
        // Инициализация списка элементов меню
        private List<MenuItem> _menuItems = new List<MenuItem>
        {
        new MenuItem{ Controller="Home", Action="Index", Text="Lab 2"},
        new MenuItem{ Controller="Product", Action="Index",
        Text="Каталог"},
        new MenuItem{ IsPage=true, Area="Admin", Page="/Index",
        Text="Администрирование"},
        new MenuItem{ IsPage=true, Area="ApiDemo", Page="/Index",
Text="API-demo"}
        };
        public IViewComponentResult Invoke()
        {
            //Получение значений сегментов маршрута
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];
            foreach (var item in _menuItems)
            {
                // Название контроллера совпадает?
                var _matchController = controller?.Equals(item.Controller)
                ?? false;
                // Название зоны совпадает?
                var _matchArea = area?.Equals(item.Area) ?? false;
                // Если есть совпадение, то сделать элемент меню активным
                // (применить соответствующий класс CSS)
                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }
    }
}

WebLab1_Levchenko/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebLab1_Levchenko.DAL.Data;
using WebLab1_Levchenko.Extensions;
using WebLab1_Levchenko.Models;

namespace WebLab1_Levchenko.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        //private string cartKey = "cart";
        private Cart _cart;

        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }

        public IActionResult Index()
        {
            //_cart = HttpContext.Session.Get<Cart>(cartKey);
            return View(_cart.Items.Values);
        }

        [Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            //_cart = HttpContext.Session.Get<Cart>(cartKey);
            var item = _context.Cats.Find(id);
            if (item != null)
            {
                _cart.AddToCart(item);
                //HttpContext.Session.Set<Cart>(cartKey, _cart);
            }
            return Redirect(returnUrl);
        }
        public IActionResult Delete(int id)
        {
            _cart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }
    }
}

WebLab1_Levchenko/Controllers/ImageController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebLab1_Levchenko.DAL.Entities;

namespace WebLab1_Levchenko.Controllers
{
    public class ImageController : Controller
    {
        UserManager<ApplicationUser> _userManager;
        IWebHostEnvironment _env;
        public ImageController(UserManager<ApplicationUser>
       userManager, IWebHostEnvironment env)
        {
            _userManager = userManager;
            _env = env;
        }
        public async Task<FileResult> GetAvatar()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user.AvatarImage != null)
                return File(user.AvatarImage, "image/...");
            else
            {
                var avatarPath = "/Images/anonymous.png";

                return File(_env.WebRootFileProvider
                .GetFileInfo(avatarPath)
               .CreateReadStream(), "image/...");
            }
        }
    }
}

WebLab1_Levchenko/Views/Shared/_Layout — копия.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebLab1_Levchenko</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                <a class="navbar-brand" href="#">90321 Левченко Т.А.</a>
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" asp-controller="Home" aspaction="Index">Lab 2</a>
                    <a class="nav-item nav-link" asp-controller="Product" aspaction="Index">Каталог</a>
                    <a class="nav-item nav-link" asp-area="Admin" asppage="/Index">Администрирование</a>
                </div>

                <!-- меню сайта - конец -->
                 Информация пользователя 
                <a href="#" class="navbar-text ml-auto">
                    00,0 руб <i class="fas fa-shopping-cart nav-color"></i> (0)
                </a>
                <div class="dropdown ml-4 nav-color">
                    <div class="dropdown-toggle" id="dropdownMenuButton"
                         data-toggle="dropdown" aria-haspopup="true"
                         aria-expanded="false">
                        <img src="Images/аватарка.jpg.jpg" width="30"
                             alt="User" class="rounded" />

                    </div>
                    <div class="dropdown-menu"
                         aria-labelledby="dropdownMenuButton">
                        <div class="dropdown-item-text">
                            <img src="Images/аватарка.jpg.jpg" width="50"
                                 alt="User" class="rounded" />
                            user@mail.ru
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Мои товары</a>
                        <a class="dropdown-item" href="#">Log off</a>
                    </div>
                </div>
                 Информация пользователя - конец 
                <!-- Информация пользователя -->
                <!--<a asp-controller="Cart" asp-action="Index" class="navbar-text mlauto">
                    00,0 руб <i class="fas fa-shopping-cart nav-color"></i> (0)
                </a>
                <div class="dropdown ml-4 nav-color">
                    <div class="dropdown-toggle" id="dropdownMenuButton"
                         data-toggle="dropdown"
                         aria-haspopup="true" aria-expanded="false">
                        <img src="~/images/avatar.jpg" width="30" alt="User"
                             class="rounded" />
                    </div>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <div class="dropdown-item-text">
                            <img src="~/images/avatar.jpg" width="50" alt="User"
                                 class="rounded" />
                            user@mail.ru
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Cart" aspaction="Index">Мои товары</a>
                        <a class="dropdown-item" asp-area="Identity"
                           asp-page="/Account/Logout">Log off</a>
                    </div>
                </div>-->
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->

            <span class="nav-color"></span>
        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main>

        @RenderBody()

    </main>

    <footer class="fixed-bottom">
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
            <span class="nav-color">Подвал страницы</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebLab1_Levchenko/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebLab1_Levchenko</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->

                <a class="navbar-brand" asp-action="Index" aspcontroller="Home">WebLabsV06</a>
                <div class="navbar-nav">
                    @await Component.InvokeAsync("Menu")
                </div>

                <!-- меню сайта - конец -->
                <!--Информация пользователя-->
                <partial name="_UserPartial" />
                <!--
                <a href="#" class="navbar-text ml-auto">
                    00,0 руб <i class="fas fa-shopping-cart nav-color"></i> (0)
                </a>
                <div class="dropdown ml-4 nav-color">
                    <div class="dropdown-toggle" id="dropdownMenuButton"
                         data-toggle="dropdown" aria-haspopup="true"
                         aria-expanded="false">
                        <img src="Images/аватарка.jpg.jpg" width="30"
                             alt="User" class="rounded" />

                    </div>
                    <div class="dropdown-menu"
                         aria-labelledby="dropdownMenuButton">
                        <div class="dropdown-item-text">
                            <img src="Images/аватарка.jpg.jpg" width="50"
                                 alt="User" class="rounded" />
                            user@mail.ru
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Мои товары</a>
                        <a class="dropdown-item" href="#">Log off</a>
                    </div>
                </div>-->
                <!-- Информация пользователя -->
                <!--<a asp-controller="Cart" asp-action="Index" class="navbar-text mlauto">
                    00,0 руб <i class="fas fa-shopping-cart nav-color"></i> (0)
                </a>
                <div class="dropdown ml-4 nav-color">
                    <div class="dropdown-toggle" id="dropdownMenuButton"
                         data-toggle="dropdown"
                         aria-haspopup="true" aria-expanded="false">
                        <img src="~/images/avatar.jpg" width="30" alt="User"
                             class="rounded" />
                    </div>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <div class="dropdown-item-text">
                            <img src="~/images/avatar.jpg" width="50" alt="User"
                                 class="rounded" />
                            user@mail.ru
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Cart" aspaction="Index">Мои товары</a>
                        <a class="dropdown-item" asp-area="Identity"
                           asp-page="/Account/Logout">Log off</a>
                    </div>
                </div>-->
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->

            <span class="nav-color"></span>
        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main>

        @RenderBody()

    </main>

    <footer class="fixed-bottom">
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
            <span class="nav-color">Подвал страницы</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
@section Scripts
{
    <script>
 var url = "@Url.Action("GetDishes", "Dishes")";
 $(document).ready(function () {
 // послать запрос
 $.getJSON(url, function (data) {
 // найти таблицу по id
 var table = $("#list");
 // сформировать строку для каждого полученного объекта
 $.each(data, function (num, value) {
 createRow(num+1, value).appendTo(table);
 })
 });
 })
// Функция формирования одной строки таблицы
 // index - порядковый номер
 // data - объект данных
 function createRow(index, data) {
 // создать строку таблицы
 var row = $("<tr>");
 // добавть колонку с порядковым номером
 row.append("<td>" + index + "</td>");
 // добавить колонку с названием
 row.append("<td>" + data.dishName + "</td>");
 // создать кнопку
 var button = $("<button>")
 .addClass("btn btn-success") // стиль кнопки
 .click(data.dishId, showDetails) // подписка на событие click
 .text("Подробно"); // надпись
 // создать колонку с кнопкой
 var td = $("<td>").append(button);
 // добавить в строку таблицы
 row.append(td);
 return row;
 }
 //Функция выода информации о выбранном объекте
 function showDetails(e) {
 // Послать запрос
 $.getJSON(url + "/" + e.data, function (data) {
 // строка информации об объекте
 var details = data.dishName + ": "
 + data.description + " - "
 + data.calories + " калорий";
 $("#info") // Найти блок для информации
 .empty() // очистить содержимое
.text(details); // записать новый текст
 })
 }
    </script>
}
</html>

WebLab1_Levchenko/Views/Shared/_UserPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Identity;
@using WebLab1_Levchenko.DAL.Entities;
@inject SignInManager<ApplicationUser> signInManager

@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")
    
    <div class="dropdown ml-4 nav-color">
        <div class="dropdown-toggle" id="dropdownMenuButton"
             data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            <img src="@Url.Action("GetAvatar","Image")"
                 width="30" alt="User"
                 class="rounded bg-light" />
            
            @*<img img-action="GetAvatar"
                 img-controller="Image"
                 width="30" alt="User"
                 class="rounded bg-light" /> не работает*@

        </div>
        <div class="dropdown-menu"
             aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                <img src="@Url.Action("GetAvatar","Image")" width="50"
                     alt="User" class="rounded" />
                @*<img img-action="GetAvatar"
                     img-controller="Image"
                     width="30" alt="User"
                     class="rounded bg-light" /> не работает*@
                @User.Identity.Name
            </div>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-controller="Product"
               asp-action="UserProducts">
                Мои
                товары
            </a>
            <form asp-area="Identity"
                  asp-page="/Account/Logout"
                  asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                <input type="submit"
                       value="Log off"
                       class="dropdown-item" />
            </form>
        </div>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Login">
                Войти
            </a>
        </li>
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Register">
                Зарегистрироваться
            </a>
        </li>
    </ul>
}




<!-- Информация пользователя -->